### ISSUE TITLE
Empty provider list

### ISSUE THREAD

**Issue by JanOppolzer** [Edugate/Jagger#102]
Although I have IdPs and SPs registered, I don't see any in the listing. ddae81990907922f52f49af89d54a1a80493675e is the last commit where everything's fine. Were there any changes in dependencies I'm missing at this moment or is it a bug?

**Comment by janul** [comment]
The providers list ir loaded via ajax and from memcache (180seconds) . There is missing small icon to force refreshing the list or/and invalidate memcache when new provider is added.
I will fix it tonight

**Comment by JanOppolzer** [comment]
This fixed the issue.

**Comment by janul** [comment]
Perfect. I still  need to add option to invalidate cache
