### ISSUE TITLE
identify & recommend strategy to enable 2 Factor Authentication

### ISSUE THREAD

**Issue by canariecaf** [Edugate/Jagger#147]
I am seeking a way to best enable 2 factor authN (2FA) for Jagger.

Specifically, I would like to use Duo security and have their library to be added and would like to have guidance and/or recommendations on how to do this.

I'm hopefull that this could be done vendor agnostic, but realistically, it will require additional libraries and some UI work on the login screen post sign on to trigger the 2nd factor to be requested.

I also see a need for 'per user' settings for 'requires' 2nd factor which may be the easiest until a way to enable it for possibly groups or more bluntly for the whole Jagger app.
The default behaviour would be to enable it per user if at all possible since that has the most fine grain control (at the expense of having to either check the box per user to enable it or walk the entire user set).

It may be equally interesting to be 'by role' (ie. do 2FA on only admins, but not clients with only IdPs), but I don't think that is easily done either.

The most blunt way is to enable it for the entire application, but that is quite punishing if you log into it multiple times daily.

I am proposing that this may be an additional configuration file '~/config/multifactor.php' 
with switches to enable/disable it and point to additional libraries.

Recommendations on where to do this is welcome.

**Comment by janul** [comment]
hi, i will do it between 18 and 24 Jan

**Comment by canariecaf** [comment]
Many thanks Janusz,

I hope my above comments and suggested specification for the 2 Factor Authentication work is sufficient. Please let me know if there are additional elements or questions for this feature enhancement for Jagger!

**Comment by janul** [comment]
ready for testing, see #152  (for the moment in develop branch)
I will close this ticket after moving it to stable branch
Documentation:
http://jagger.heanet.ie/jaggerdocadmin/authentication.html#two-factor-authentication

**Comment by canariecaf** [comment]
I've successfully signed with a regular user account in my dev instance of Jagger.

That said, the ability for a user to 'self-enable' duo is present on their profile page.  When I sign in as a NON admin user, I cannot have the my duo selection 'saved' I get a 403 error in the chrome developer console when it tries to persist the setting.  It appears that the  the modelsAclRole.php gets rewritten with a different permission??
-rw-r--r--. 1 apache apache  8014 Jan 29 15:33 __CG__modelsAclRole.php
      ^^^^^^  and won't execute for some reason?  

From a policy perspective, it's an interesting question about the end user enabling/disabling it. 
It may be that from system level we want that to have Duo, or maybe MINIMUM a 2nd factor if not duo, yubikey maybe? 

This is an interesting question -- should the user be even allowed to change the 2nd factor profile at all (ie disable/enable it?)  Maybe not at this stage of the game.  If the system REQUIRES 2nd factor, it would have been administratively enabled and therefore not under the users control.

Thoughts/comments welcome here.

(I did delete my proxies directory so I started from a clean slate.

**Comment by canariecaf** [comment]
Oops, I also should mention I have not tried from a Federated sign on perspective yet.  That's next.

**Comment by janul** [comment]
Thanks for testing, 
Yes, for now only (develop branch) admins can set 2f in users profile. I'm not sure what would be the best practice in this case. I'm also working on webbased global preferences page so maybe it would be good place to allow admin to decide if ordinary user can change authentication method or his request should go for approval. also youbikey will be available by the end of next week (I hope:))
I also think user should be notified by email if such settings have been changed on his profile.

About proxies - if you have set 
define ('ENVIRONMENT', 'development');   in index.php file - doctrine should update them automaticaly (i most cases - I remember there was some issue when docitrine core has been updated)
otherwise you need to regenerate them manually if the code has been changed in models files
