### ISSUE TITLE
Metadata comment at top of aggregate has an extranous 'n' 

### ISSUE THREAD

**Issue by canariecaf** [Edugate/Jagger#167]
Going through a side by side inspection of the aggregate shows that the header comment has an extranous 'n' in it:

It is suspected that this is a \n without the prefix of the backslash to for a carriage return.

**Comment by janul** [comment]
do you mean the first comment
..nMetadata was generated on... 
?
This "n" was added intentionaly during my change from DOM to XMLwriter to distinguish what library was used. I'll remove it.
Thanks,
Janusz

**Comment by canariecaf** [comment]
Yes. When examining the metadata it looks a bit odd without your explanation :)
I'm going through the differences in the aggregates we currently have and what Jagger will generate to be very sure we know what we will be publishing.

Thanks!
