### ISSUE TITLE
potential creation of multiple registration policies on aggregate import, unknown who it links to.

### ISSUE THREAD

**Issue by canariecaf** [Edugate/Jagger#168]
We had imported our federation aggregate and the registration policy section created multiple entries on the same record:
![image](https://cloud.githubusercontent.com/assets/5281413/6466961/2f4f1526-c199-11e4-83e7-38250d8e7986.png)

Now, I cannot enable a policy that has a duplicate (good thing):
![image](https://cloud.githubusercontent.com/assets/5281413/6466996/72497a42-c199-11e4-8f8b-01ae940d4dad.png)

I can go and delete the colliding elements so there is the appropriate limited, unique list but I believe this should not happen in the first place.
I suspect it's from the aggregate import process and may not collapse/map existing registration policies as best as it could.
I have a work around for this right now so it is not a critical issue at this time.

**Comment by janul** [comment]
Thank you for filing the bug. I fix it asap

**Comment by janul** [comment]
after update please run Admini->migration - it will fix existing collection 
later I will add feature to show all providers connected to policies
