### ISSUE TITLE
Grammar error in a pop-up message

### ISSUE THREAD

**Issue by spaetow** [Edugate/Jagger#213]
Hi, 
![screen shot 2015-06-15 at 17 16 11](https://cloud.githubusercontent.com/assets/4982349/8163388/01585c40-1383-11e5-9867-5c81cdd0a79e.png)

I can't seem to find this string anywhere... is it being constructed from several strings?

**Comment by janul** [comment]
no, it's directly from js. I'm going to move it into modal and then string will be available

**Comment by spaetow** [comment]
Ahhh, thanks. Simply respond here and I'll fix it :-)

**Comment by janul** [comment]
string is set $lang['nometainsertnotice']
