### ISSUE TITLE
Deleting a user not possible

### ISSUE THREAD

**Issue by JanOppolzer** [Edugate/Jagger#235]
I can't delete federated user's account in the latest version of 1.x-stable branch (d8893743694e12e4fb3b114cc9f948cd6f3a8e1d). After filling in the username, I just get `An Error Was Encountered` message with no useful information in the log file even when logging everything (`$config['log_threshold'] = 4;` in config.php).

**Comment by janul** [comment]
Unfortunately I cannot reproduce it. I will contact you directly

**Comment by janul** [comment]
It stopped working with recent rev of Codeigniter core:
the last CI rev which works is 175b17c
I need to take deeper look

**Comment by janul** [comment]
removing user is fixed (caused by js bug)
