### ISSUE TITLE
rr3sess* files flooding /tmp

### ISSUE THREAD

**Issue by andrius-kulbis** [Edugate/Jagger#267]
Hi,

The /tmp folder is flooder with rr3sess\* files every day. There is 17k files for two past days with the content similar to: 
`__ci_last_regenerate|i:1468867232;`

Is it a misconfiguration or some cronjob is required to deal with the deletion of these files?

**Comment by janul** [comment]
hi, 
I'll take a look at it today.

**Comment by janul** [comment]
I presume you have set custom location for session : `$config['sess_save_path']`
If so then you need to add something like this:
`10,40 * * * *  root  [ -x /usr/lib/php5/maxlifetime ] && [ -x /usr/lib/php5/sessionclean ] && [ -d PATH_TO_JAGGER_SESSION_FILES ] && /usr/lib/php5/sessionclean PATH_TO_JAGGER_SESSION_FILES $(/usr/lib/php5/maxlifetime)`
