### ISSUE TITLE
Add support for Sirtfi

### ISSUE THREAD

**Issue by hannahshort** [Edugate/Jagger#269]
As discussed with Janusz, the Sirtfi REFEDS Working Group has recently defined 2 metadata additions to show adoption of Sirtfi (the Security Incident Response Trust Framework for Federated Identity). Please could you add support to Jagger for handling these two metadata additions (1 attribute profile extension and one custom contactPerson)? Info on the wiki: https://wiki.refeds.org/display/SIRTFI/Guide+for+Federation+Participants

**Comment by janul** [comment]
after update please do not forget tu run doctrine-cli to update schema and proxies:
go to jagger application folder and run:

to  update db contact table run:
`./doctrine orm:schema-tool:update --force`

to regenerate application/models/Proxies:
`./doctrine orm:generate:proxies`

and make sure that folder application/models/Proxies and included files are writeable by apache

To enable sirfti:
Via UI got to **Menu::Administration::Entity Attributes**  and add (if not done already):
DisplayName: _SIRFTI (or whatever you like)_
Attribute name : _urn:oasis:names:tc:SAML:attribute:assurance-certification_
Value: _https://refeds.org/sirtfi_
enabled: _tick_

Then entities owners need to apply for it via entityedit. they need to add sirfty contact too.
