### ISSUE TITLE
Missing metadata properties

### ISSUE THREAD

**Issue by andrius-kulbis** [Edugate/Jagger#281]
There is a checkbox to set the `WantAssertionSigned` option in UI. What about other possible properties like `AuthnRequestsSigned`? Also is it possible to mark that service provider wants encrypted assertion?

**Comment by janul** [comment]
Thanks for suggestion Andrius. As soon I finish other pieces I'm working on I will add it too.

**Comment by janul** [comment]
after update you need update db schema by running commands:
`./doctrine orm:schema-tool:update`
`./doctrine orm:generate:proxies
`
