### ISSUE TITLE
Approving a new entity as a federation administrator doesn't assign permissions

### ISSUE THREAD

**Issue by JanOppolzer** [Edugate/Jagger#290]
In case a user has full permissions for a federation (`read`, `write`, `manage` and `approve`), it is still not possible for him to assign permissions to an entity registrator while approving a new entity to the federation. The entity registrator still has only `read` permission regardless of permissions set while approving the entity. Only Jagger `administrator` can assign permissions. Is it a bug or am I missing something?

**Comment by janul** [comment]
That might be missing functionality. I take a look at it.

**Comment by JanOppolzer** [comment]
I'm just looking at it and found the following:
https://github.com/Edugate/Jagger/blob/e59f6f2a2c619abe05071d596f5697e80d3f3835/application/controllers/reports/Awaiting.php#L444

I'll keep digging tomorrow 😎 .

**Comment by JanOppolzer** [comment]
I have found a possible solution to this issue, but I'm not sure that it's the right way to fix it. I don't like changing `add_access_toUser()` function. See 0c215a787a718f260b8e650c5fe4f4ae060f5758

**Comment by JanOppolzer** [comment]
Works well, thank you.
