### ISSUE TITLE
Unable to locate metadata for identity provider

### ISSUE THREAD

**Issue by lindaagustina** [Edugate/Jagger#303]
Hi,

I want to ask something, I want to connecting IDP and SP using Jagger. I following this tutorial https://jagger.heanet.ie/jaggerdocadmin/metadata.html.
But doesn't work, and I found error message
opensaml::saml2md::MetadataException
The system encountered an error at Thu Dec 12 09:14:00 2019

To report this problem, please contact the site administrator at root@localhost.

Please include the following message in any email:

opensaml::saml2md::MetadataException at (https://sso-sp.x.x.x/Shibboleth.sso/Login)

Unable to locate metadata for identity provider (https://jagger.x.x.x/rr3/metadata/circle/ENCODE_ENTITYID/metadata.xml)

I hope someone in here can help me.

**Comment by janul** [comment]
This is shibboleth misconfiguration. I will answer to it on mailing list when have spare moment
