### ISSUE TITLE
Add Requirements Signaling for SAML-SubjectID-v1.0

### ISSUE THREAD

**Issue by martinsta** [Edugate/Jagger#313]
Jagger RR3 currently caters for EntityAttributes that carry Entity Category (entcat) like information. May I suggest a registry enhancement to allow for subject identification requirements signalling [SAML-SubjectID-v1.0], i.e. to enable working with "urn:oasis:names:tc:SAML:profiles:subject-id:req" attribute(s) in the <mdattr:EntityAttributes> extension?

Comments are welcome.

[SAML-SubjectID-v1.0]
SAML V2.0 Subject Identifier Attributes Profile Version 1.0
3.5.1      Requirements Signaling
https://docs.oasis-open.org/security/saml-subject-id-attr/v1.0/cs01/saml-subject-id-attr-v1.0-cs01.html#_Toc536097237

**Comment by janul** [comment]
Thank you for your suggestion. I will check that.
