### ISSUE TITLE
Can't specify multiple ACS URLs, ... while registering a new Service Provider

### ISSUE THREAD

**Issue by JanOppolzer** [Edugate/Jagger#50]
Registering a new Service Provider doesn't allow to specify more than one AssertionConsumerService URL. ArtifactResolutionService, SingleLogoutService and other URLs can't be defined at all.

Yes, it's possible to add all those URLs later when the new SP is approved (Service Providers > List > "choose a SP" > Service Locations > edit); however, it'd be much better if all URLs are specified before sending the new SP to approve. A person approving the request would be able to check whether all information is correct to prevent any possible issues.

**Comment by janul** [comment]
multiple AssertionConsumerService urls are now populated after parsing xml from metadata field.
ArtifactResolutionService, SingleLogoutService and other URLs will be added within couple of next commits
