### ISSUE TITLE
AssertionConsumingService not generated for SP required attributes

### ISSUE THREAD

**Issue by malavolti** [Edugate/Jagger#73]
Hi Janusz,
with the help of a my collegue, Simona Venuti, I've discovered that the portion of SP metadata related on md:AttributeConsumingService (that includes the md:RequestedAttribute, md:ServiceName, md:ServiceDescription) is not generated when I complete the Attribute Tab for my SP.

I've tried to complete also the UII Tab, but without success. :(

This is a Bug or I have forgot to do something?

Best Regards,
Marco

**Comment by janul** [comment]
Can you check federation metadata (with checked option "include required attributes")
Does you entity contains  these elements ?

**Comment by malavolti** [comment]
On Federation Metadata those elements there are (after I checked the option "include required attributes" into Federation Basic Information form), but on Service Metadata of SPs they are not.

**Comment by janul** [comment]
OK, It's not implemented into circle metadata yet
