### ISSUE TITLE
Problems with metadata parser

### ISSUE THREAD

**Issue by malavolti** [Edugate/Jagger#75]
Hi,

I think there are some problems with the parsing of SP metadata on the metadata parser...

I've tried to parse an SP metadata and I have seen that several xml TAGs are not parsed completely.
After the parsing I see mdui:displayName and mdui:InformationURL only for english language and not for the other languages and every mdui:Description, mdui:PrivacyStatementURL, mdui:Logo, init:RequestInitiator, idpdisc:DiscoveryResponse, md:ArtifactResolutionService, md:SingleLogoutService,  md:ManageNameIDService is disappeared into "Service metadata url" and into Federation's Metadata.

Even for md:OrganizationName, md:OrganizationURL and md:OrganizationDescription I see only the english value and not the others.

There is some way to import the different (technical, administrative, support, billing) contacts into metadata automatically with the parser?

Thank you so much Janusz!!!

**Comment by janul** [comment]
simple registration form will be removed
