### ISSUE TITLE
Federation Validator

### ISSUE THREAD

**Issue by JanOppolzer** [Edugate/Jagger#78]
Hi, I've created a number of XSDs to validate metadata against, but now I can't figure out how to use Federation Validator to use them. Is there any documentation I can read in order to understand how it works?

**Comment by JanOppolzer** [comment]
Thank you, @janul for your help via e-mail. Are you interested in helping you with documentation? I'd write a howto (Wiki section here at GitHub?) if you'd welcome that... Someone might find useful the information you've provided to me.

**Comment by janul** [comment]
Thank you Jan, that's very nice . If you really have time so then you could own docs into https://github.com/Edugate/Documentation
