### ISSUE TITLE
APC cache and PHP 5.5 compatibility 

### ISSUE THREAD

**Issue by ivan-novakov** [Edugate/Jagger#91]
Currently the APC cache is being used for a "production" environment by default. Maybe the caching system should be at least configurable explicitly, because for example APC is not available under PHP 5.5.

https://github.com/Edugate/ResourceRegistry/blob/002a65ff338b9ada9d922932bd92746ffbd32487/application/libraries/Doctrine.php#L51

My current workaround is to specify an alternative "production_without_apc" environment in `index.php` to avoid using the APC cache.

**Comment by janul** [comment]
Thank u, i fix it when i'm back from my holiday next week.

**Comment by janul** [comment]
tested with apcu and it seems to work fine
