### ISSUE TITLE
How to set the default language?

### ISSUE THREAD

**Issue by ivan-novakov** [Edugate/Jagger#98]
Is there a working option to set a default language different from "english"? I tried the _language_ directive in `config.php` and the _langselectdefault_ directive in `config_rr.php` but none of them worked.

The expected behaviour is to have the default language pre-selected, when you first visit the site. That means - before you got the `rrlang` cookie.

**Comment by janul** [comment]
if you mean  jagger ui then $config['rr_lang'] = 'cs' should work

for default lang in dropdown select in edit mode: $config['langselectdefault']  should work

I just tested them and they're work fine? Can you check above options ?

**Comment by ivan-novakov** [comment]
Yes, the `rr_lang` directive does the trick, thanks!
But it should be included somewhere in the default config files. For now it's practically "hidden" :).

**Comment by janul** [comment]
you're right
The closing issue #8 should solve - I hope it happens within 3 weeks
